#!/bin/bash

day=$1

# Keep session key here
. cookies.sh

wget --no-cookies --header "Cookie: session=$SESSION" https://adventofcode.com/2021/day/$day/input -O data/day$day.txt

git add data/day$day.txt

if [ ! -f examples/day${day}.rs ]; then
    sed -e "s/\\\$N/$day/g" < examples/template.rs > examples/day${day}.rs
    git add examples/day${day}.rs
fi
git commit -m"Add day $day input" data/day$day.txt
